name: CI

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22.18.0' # Voltaでpinしたバージョンに合わせる
          cache: 'pnpm'

      - uses: pnpm/action-setup@v4
        with:
          version: '10.4.0' # packageManager と合わせる

      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22.18.0'
          cache: 'pnpm'

      - uses: pnpm/action-setup@v4
        with:
          version: '10.4.0'

      - run: pnpm install --frozen-lockfile
      - run: pnpm run format:check
