name: ci

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - run: node -v
      - run: pnpm -v
      - run: pnpm list --depth 0
      - run: pnpm install --frozen-lockfile
      - run: pnpm -s lint
